In [67]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot  as plt
import warnings
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import seaborn as sns
warnings.filterwarnings("ignore")

In [16]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.fillna("")

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,,Reg,Lvl,AllPub,...,0,,,,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,,Reg,Lvl,AllPub,...,0,,,,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,,IR1,Lvl,AllPub,...,0,,,,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,,IR1,Lvl,AllPub,...,0,,,,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,,IR1,Lvl,AllPub,...,0,,,,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,,Reg,Lvl,AllPub,...,0,,,,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,,Reg,Lvl,AllPub,...,0,,MnPrv,,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,,Reg,Lvl,AllPub,...,0,,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,,Reg,Lvl,AllPub,...,0,,,,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,,Reg,Lvl,AllPub,...,0,,,,0,6,2008,WD,Normal,147500

In [4]:
train.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [44]:
la= LabelEncoder()

In [126]:
dobject=train.select_dtypes(include="object")
nobject=train.select_dtypes(exclude="object")

AttributeError: 'NoneType' object has no attribute 'select_dtypes'

In [27]:
nobject.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [28]:
nobject.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [30]:
nobject.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [41]:
df = pd.DataFrame(nobject)
imp = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

df_imputed = pd.DataFrame(imp.fit_transform(df),columns=df.columns)

In [46]:
for i in range(0,dobject.shape[1]):
     dobject.iloc[:,i]=la.fit_transform( dobject.iloc[:,i])

In [53]:
ntrain=pd.concat([dobject,nobject],axis=1)

In [61]:
ntrain.isnull().sum()

MSZoning       0
Street         0
Alley          0
LotShape       0
LandContour    0
              ..
PoolArea       0
MiscVal        0
MoSold         0
YrSold         0
SalePrice      0
Length: 81, dtype: int64

In [62]:
ntrain.head(20)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,3,1,2,3,3,0,4,0,5,2,...,0,61,0,0,0,0,0,2,2008,208500
1,3,1,2,3,3,0,2,0,24,1,...,298,0,0,0,0,0,0,5,2007,181500
2,3,1,2,0,3,0,4,0,5,2,...,0,42,0,0,0,0,0,9,2008,223500
3,3,1,2,0,3,0,0,0,6,2,...,0,35,272,0,0,0,0,2,2006,140000
4,3,1,2,0,3,0,2,0,15,2,...,192,84,0,0,0,0,0,12,2008,250000
5,3,1,2,0,3,0,4,0,11,2,...,40,30,0,320,0,0,700,10,2009,143000
6,3,1,2,3,3,0,4,0,21,2,...,255,57,0,0,0,0,0,8,2007,307000
7,3,1,2,0,3,0,0,0,14,4,...,235,204,228,0,0,0,350,11,2009,200000
8,4,1,2,3,3,0,4,0,17,0,...,90,0,205,0,0,0,0,4,2008,129900
9,3,1,2,3,3,0,0,0,3,0,...,0,4,0,0,0,0,0,1,2008,118000
10,3,1,2,3,3,0,4,0,19,2,...,0,0,0,0,0,0,0,2,2008,129500
11,3,1,2,0,3,0,4,0,16,2,...,147,21,0,0,0,0,0,7,2006,345000
12,3,1,2,1,3,0,4,0,19,2,...,140,0,0,0,176,0,0,9,2008,144000
13,3,1,2,0,3,0,4,0,5,2,...,160,33,0,0,0,0,0,8,2007,279500
14,3,1,2,0,3,0,0,0,12,2,...,0,213,176,0,0,0,0,5,2008,157000
15,4,1,2,3,3,0,0,0,3,2,...,48,112,0,0,0,0,0,7,2007,132000
16,3,1,2,0,3,0,1,0,12,2,...,0,0,0,0,0,0,700,3,2010,149000
17,3,1,2,3,3,0,4,0,19,2,...,0,0,0,0,0,0,500,10,2006,90000
18,3,1,2,3,3,0,4,0,20,5,...,0,102,0,0,0,0,0,6,2008,159000
19,3,1,2,3,3,0,4,0,12,2,...,0,0,0,0,0,0,0,5,2009,139000

In [104]:
x=ntrain.drop("SalePrice",axis=1)
y=ntrain["SalePrice"]
#ff=["PoolArea","LotArea"]
xtest=test[ff]

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('regressor', LinearRegression())
])

In [81]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer()),
                ('regressor', LinearRegression())])

In [116]:
predictions = pipeline.predict(x_test)
print(predictions)

[148868.97396652 318551.24214985 110498.47595245 180838.99747321
 313295.83011369  74707.48943631 231488.26317609 147008.93829262
  73862.90629527 152440.68810891 152223.04901474 107366.08705384
  73657.268049   208342.03074922 165739.07636793 137479.26841152
 214142.25083989 115107.40437936 114088.35946549 231622.95231113
 132650.50242663 209331.03763604 189264.18304356 118302.3358933
 218672.43825723 162140.26072926 211481.59960342  73813.19309783
 164859.71564537 198445.33771503 164539.33435503 257116.8532957
 176863.75768787 102237.07102583 251908.9159602  148388.51204892
 119261.60303639 218120.26153174 290336.23541133  92579.30735848
 116320.89976793 253676.26352248 111368.52497934 320462.17947381
 124886.92455767 150630.50113946  94628.49581255 135579.31260255
 395277.98167968 123282.81419096 116399.92419858 216339.82870792
 103632.18366877 361150.47308083 152376.4355643  244494.77701978
 223677.41359146 182774.13029214 131227.20844945  97878.76995691
  29075.18899994 157642.27285617 306704.75826994 264815.52898768
 279908.0947485  222322.96924208 106796.56502489 303720.14722508
 107670.31348452 188770.14758157 115864.23203981 135519.47805622
  98631.72689573  64159.00563029 419242.68817793 174714.84442213
 275977.56914223 286819.67043865 141989.68683912 115041.91032654
 132131.77064838  61742.34607519 117805.89675628 132975.4444027
 160906.89636988 137272.08053509 259950.37722084 204484.17939066
 152196.39460292 196961.45999351 122305.48241384 115966.55411814
 125490.39310995 263854.30220183 112054.53729239 191056.97716704
 197286.11213232 195075.0421459  212990.40140236 285334.00970472
 183043.87772385 215281.98535354 298377.21065323 133531.33618618
 197888.89169445 178953.85060003 168328.5280184  244641.6625988
 133777.00410306 232631.50275863  40837.42923857 114076.27169669
 141685.04167093 119280.95285244 221927.96394069 120975.89216692
  96570.75477954 117470.34964472 145545.14407178 254843.30548168
 136720.19367386 154344.53594022 179387.09793611 176395.54161635
 189899.38965906 129087.13945104 236749.12596777  83376.75110919
 141226.13436767 194089.07203478 193567.79152346 324794.64773691
 197023.10650125 114357.01526268  55456.52581673 354886.66356835
 344157.72203776 141437.37181278 237863.24737318 532144.23172458
 296904.20368259 125247.90481821 200298.03995924 162214.56698853
 104872.08814018 121372.86607809 221880.3588393  197387.86975626
 108358.2149554   42409.48007474 124426.71833984 145393.13775957
 201772.38889913 166748.21437218  61213.58731145 114407.11559459
 134634.98386596 140294.89968989  81918.74118992 141582.32452777
 230143.32162606 122900.5232583  282666.36592184 163053.82235526
 104547.00529276 115571.87543871 291235.51352204 330452.4762904
 385362.82130369 211217.97642732 346757.16508935  82258.11508486
  89345.35192756 160780.27116325 294137.33946621 100852.38986261
 124184.89859081 237087.27699806 119409.90083162 162008.25735917
 162529.54397325 138730.93602422 125302.4537437  138748.27709004
 241683.04700584 171007.16129699 274713.22312176 225205.41143001
 193489.71047159  72387.75613258 111042.44063503 111403.4123958
 106390.43915196  48181.7781328  207906.27539696 205225.2284038
 206513.69272646  79251.34642242 221095.81802376 123527.39762825
 283499.31208853 191306.71989048  96847.74546368 289490.67258752
 206535.64686936 110555.72624448 239793.53030194 130911.99409444
 142056.57599024  87503.46514145 254834.24667655 155553.87344501
 113968.65661542 173076.41856665 229716.343319   251813.80125478
 212196.43743111 126668.86532352  91610.82978587 141877.30621502
 146484.65290478 215599.28072194 202155.26306614  95091.76938556
 238227.01591416 147591.37193702  91228.02920293  71022.07046826
 178539.04621938 100501.57055613  94356.13860485 179459.5709738
 122163.13804648 116746.55453316 246945.48358754 132868.59564641
 200489.28879629 175172.22688488 255571.60665847 117650.09163361
 120813.03579987 309649.96748365 239493.95180001 405290.62487987
 201057.46664026 104298.98550791 166952.90958571 187513.83742244
 147608.66715104  95198.88619172 186989.76399314 191037.92110161
 128092.72687633 118736.93456298 149646.94873171 135193.28692481
 104476.52245535 111510.11469378 190943.73298613 250015.57934499
 283025.61016354 194192.29244349 121002.93362532 241657.12107246
 341097.54590713 231888.1366794  187687.58678515 144251.47028356
 115995.39675285 179967.64093106 358854.54370353 212321.52889483
 232224.29475341  77228.96051029  91429.24378547 126075.20773129
 156825.79648043 302881.31914731 263319.48705008 128499.33585596
 207739.27129738 113072.05960287 196040.10219044 118655.95876067
 299645.39402481 190283.35264715 207721.80448498 138373.9095592
 266260.82397714 217086.57377296 116013.36783458 108958.43907537]

In [84]:
test.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [92]:
dobjectest=test.select_dtypes(include="object")
nobjectest=test.select_dtypes(exclude="object")
for i in range(0,dobject.shape[1]):
     dobjectest.iloc[:,i]=la.fit_transform( dobjectest.iloc[:,i])

In [96]:
ntest=pd.concat([dobjectest,nobjectest],axis=1)
ntest.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,2,1,2,3,3,0,4,0,12,1,...,730.0,140,0,0,0,120,0,0,6,2010
1,3,1,2,0,3,0,0,0,12,2,...,312.0,393,36,0,0,0,0,12500,6,2010
2,3,1,2,0,3,0,4,0,8,2,...,482.0,212,34,0,0,0,0,0,3,2010
3,3,1,2,0,3,0,4,0,8,2,...,470.0,360,36,0,0,0,0,0,6,2010
4,3,1,2,0,1,0,4,0,22,2,...,506.0,0,82,0,0,144,0,0,1,2010

In [97]:
ntest.isnull().sum()

MSZoning       0
Street         0
Alley          0
LotShape       0
LandContour    0
              ..
ScreenPorch    0
PoolArea       0
MiscVal        0
MoSold         0
YrSold         0
Length: 80, dtype: int64

In [108]:
dff = pd.DataFrame(ntest)
impp = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

df_imputed = pd.DataFrame(impp.fit_transform(dff),columns=dff.columns)

In [105]:
ff=ntest

In [ ]:
test_predictions = pipeline.predict(ff)

In [107]:
print(test_predictions)

[205729.38040398 254848.67843513 265648.36347954 ... 237056.67224372
 212968.24007354 336657.68343936]